// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_8Q9IDkfqmAoEPKdSFcp5K_uu15WWR8k',
    appId: '1:568504583347:web:bba2f1a715211e25e71cc6',
    messagingSenderId: '568504583347',
    projectId: 'property-management-app-c0266',
    authDomain: 'property-management-app-c0266.firebaseapp.com',
    storageBucket: 'property-management-app-c0266.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE5cdCXBcmmCsLoiU2XUtv954Z0LTy_DM',
    appId: '1:568504583347:android:bfae14a75a5cc628e71cc6',
    messagingSenderId: '568504583347',
    projectId: 'property-management-app-c0266',
    storageBucket: 'property-management-app-c0266.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxBWazKaCe4KMj9yoRrX057aFq-dJcriQ',
    appId: '1:568504583347:ios:7faefca88c8c1c44e71cc6',
    messagingSenderId: '568504583347',
    projectId: 'property-management-app-c0266',
    storageBucket: 'property-management-app-c0266.firebasestorage.app',
    iosBundleId: 'com.example.propertyManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxBWazKaCe4KMj9yoRrX057aFq-dJcriQ',
    appId: '1:568504583347:ios:7faefca88c8c1c44e71cc6',
    messagingSenderId: '568504583347',
    projectId: 'property-management-app-c0266',
    storageBucket: 'property-management-app-c0266.firebasestorage.app',
    iosBundleId: 'com.example.propertyManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_8Q9IDkfqmAoEPKdSFcp5K_uu15WWR8k',
    appId: '1:568504583347:web:c1b6e19642609245e71cc6',
    messagingSenderId: '568504583347',
    projectId: 'property-management-app-c0266',
    authDomain: 'property-management-app-c0266.firebaseapp.com',
    storageBucket: 'property-management-app-c0266.firebasestorage.app',
  );
}
